### ISSUE TITLE
Shorter Solution: 74 Bytes

### ISSUE THREAD

**Issue by catearcher** [makeusabrew/novalidate#1]
You can set the value of the `novalidate` attribute to `i`, and you don't need the trailing semicolon.

`for(var f=document.forms,i=f.length;i--;)f[i].setAttribute("novalidate",i)`

**Comment by rdetert** [comment]
Setting a value to `novalidate` also fixes the problem in Firefox [#2]

**Comment by makeusabrew** [comment]
:heart:

**Comment by makeusabrew** [comment]
Now proudly displayed on the home page. Thanks @catearcher!
